import * as React from 'react';
import styled from 'styled-components';

const MovieTrailerBlock = styled.div`
  background: black;
  display: flex;
  box-shadow: 0 2px 12px 0 rgba(0, 0, 0, 0.9);
  margin-left: 64px;
  margin-bottom: 1rem;
  flex-wrap: wrap;
  height: 430px;
  .movieTrailer {
    width: 900px;
  }
  .boxOffice {
    flex: 1;
    padding: 1.5rem;
    display: flex;
    flex-direction: column;
    .title {
      color: #eeeeee;
      font-size: 15px;
      height: auto;
      margin: 0 0 20px 0;
      background: none;
      line-height: 1.2;
      text-align: left;
    }
    .rank {
      display: flex;
      flex-direction: column;
      color: #666666;
      span {
        font-size: 0.875rem;
        margin: 0.5rem 0;
      }
    }
  }
`;
export interface MovieTrailerProps {
  movie: any;
}

// Generated by https://quicktype.io

const MovieTrailer: React.FC<MovieTrailerProps> = ({ movie }) => {
  console.log(movie);
  return (
    <MovieTrailerBlock>
      <div className="movieTrailer">영상 틀자</div>
      <div className="boxOffice">
        <div className="title">박스오피스</div>
        <div className="rank">
          {movie.map((movie: any, index: number) => (
            <span>
              {movie.rnum} {movie.movieNm}{' '}
            </span>
          ))}
        </div>
      </div>
    </MovieTrailerBlock>
  );
};

export default MovieTrailer;
